global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: supabase-analytics
    scheme: http
    metrics_path: /v0/projects/tevpilxmtireovykrqcu/analytics/metrics
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/token
    static_configs:
      - targets:
          - mgmt-api.infrastructure.orb.local:8080
