defmodule Logflare.CredoChecks.ReplicatedDdlExecute do
  use Credo.Check,
    category: :warning,
    base_priority: :high,
    param_defaults: [
      ddl_prefixes: ["create", "alter", "drop", "rename"],
      node_local_patterns: [
        "publication",
        "subscription",
        "replica identity",
        "alter system",
        "alter user"
      ]
    ],
    explanations: [
      check: """
      Raw `execute/1` SQL strings in a migration are NOT replicated to pglogical
      subscribers, while DDL generated by the Ecto migration DSL is. A migration that
      mixes the two leaves subscribers with a half-applied schema, which stalls the
      apply worker.

      Wrap DDL strings so they are replicated:

          # preferred

          Migrator.with_replicated_execute(fn ->
            execute("ALTER TABLE sources DROP CONSTRAINT sources_user_id_fkey")

            alter table(:sources) do
              modify(:user_id, references(:users, on_delete: :delete_all))
            end
          end)

          # NOT preferred

          execute("ALTER TABLE sources DROP CONSTRAINT sources_user_id_fkey")

          alter table(:sources) do
            modify(:user_id, references(:users, on_delete: :delete_all))
          end

      Both the up and down SQL of `execute/2` are checked, and leading SQL comments or
      preceding statements (`SET ...; CREATE ...`) do not hide a DDL statement.

      Statements matching `:node_local_patterns` (publications, subscriptions, replica
      identity, `ALTER SYSTEM`, role changes) are ignored: those configure the node or
      cluster itself and must not be replicated.
      """,
      params: [
        ddl_prefixes: "Leading SQL keywords that mark a statement as replicable DDL.",
        node_local_patterns: "Statements containing these whole words are node-local and exempt."
      ]
    ]

  alias Logflare.CredoChecks.ReplicatedExecuteScope

  @impl true
  def run(%SourceFile{} = source_file, params) do
    issue_meta = IssueMeta.for(source_file, params)
    ddl_prefixes = Params.get(params, :ddl_prefixes, __MODULE__)

    node_local_regexes =
      params
      |> Params.get(:node_local_patterns, __MODULE__)
      |> Enum.map(&Regex.compile!("\\b" <> Regex.escape(String.downcase(&1)) <> "\\b"))

    rules = %{
      issue_meta: issue_meta,
      ddl_prefixes: ddl_prefixes,
      node_local_regexes: node_local_regexes
    }

    source_file
    |> SourceFile.ast()
    |> ReplicatedExecuteScope.walk([], &collect_issues(&1, &2, &3, rules))
    |> Enum.reverse()
  end

  defp collect_issues(
         {:execute, meta, arguments},
         %ReplicatedExecuteScope{replicated?: false},
         issues,
         rules
       )
       when is_list(arguments) do
    for sql when is_binary(sql) <- Enum.map(arguments, &sql_text/1),
        replicable_ddl?(sql, rules.ddl_prefixes, rules.node_local_regexes),
        reduce: issues do
      issues -> [issue_for(rules.issue_meta, meta, sql) | issues]
    end
  end

  defp collect_issues(_node, _env, issues, _rules), do: issues

  defp sql_text(sql) when is_binary(sql), do: sql
  defp sql_text({:<<>>, _meta, parts}), do: Enum.map_join(parts, &sql_part/1)

  defp sql_text({sigil, _meta, [sql, _mods]}) when sigil in [:sigil_s, :sigil_S],
    do: sql_text(sql)

  defp sql_text(_argument), do: nil

  defp sql_part(part) when is_binary(part), do: part
  defp sql_part(_interpolation), do: "..."

  defp replicable_ddl?(sql, ddl_prefixes, node_local_regexes) do
    sql
    |> String.replace(~r/--[^\n]*/, " ")
    |> String.replace(~r/\/\*.*?\*\//s, " ")
    |> String.split(";")
    |> Enum.map(&normalize/1)
    |> Enum.any?(fn statement ->
      Enum.any?(ddl_prefixes, &String.starts_with?(statement, &1 <> " ")) and
        not Enum.any?(node_local_regexes, &Regex.match?(&1, statement))
    end)
  end

  defp normalize(sql) do
    sql
    |> String.trim()
    |> String.downcase()
    |> String.replace(~r/\s+/, " ")
  end

  defp issue_for(issue_meta, meta, sql) do
    format_issue(
      issue_meta,
      message:
        "Wrap `#{sql |> String.trim() |> String.slice(0, 40)}` in Logflare.Repo.Migrator.with_replicated_execute/1 so it is replicated to pglogical subscribers.",
      line_no: meta[:line],
      column: meta[:column]
    )
  end
end
