defmodule Logflare.CredoChecks.ReplicatedDdlExecute do
  use Credo.Check,
    category: :warning,
    base_priority: :high,
    param_defaults: [
      ddl_prefixes: ["create", "alter", "drop", "rename"],
      node_local_patterns: [
        "publication",
        "subscription",
        "replica identity",
        "alter system",
        "alter user"
      ]
    ],
    explanations: [
      check: """
      Raw `execute/1` SQL strings in a migration are NOT replicated to pglogical
      subscribers, while DDL generated by the Ecto migration DSL is. A migration that
      mixes the two leaves subscribers with a half-applied schema, which stalls the
      apply worker.

      Wrap DDL strings so they are replicated:

          # preferred

          Migrator.with_replicated_execute(fn ->
            execute("ALTER TABLE sources DROP CONSTRAINT sources_user_id_fkey")

            alter table(:sources) do
              modify(:user_id, references(:users, on_delete: :delete_all))
            end
          end)

          # NOT preferred

          execute("ALTER TABLE sources DROP CONSTRAINT sources_user_id_fkey")

          alter table(:sources) do
            modify(:user_id, references(:users, on_delete: :delete_all))
          end

      Statements matching `:node_local_patterns` (publications, subscriptions, replica
      identity, `ALTER SYSTEM`, role changes) are ignored: those configure the node or
      cluster itself and must not be replicated.
      """,
      params: [
        ddl_prefixes: "Leading SQL keywords that mark a statement as replicable DDL.",
        node_local_patterns: "Statements containing these are node-local and exempt."
      ]
    ]

  alias Logflare.CredoChecks.ReplicatedExecuteScope

  @impl true
  def run(%SourceFile{} = source_file, params) do
    issue_meta = IssueMeta.for(source_file, params)
    ddl_prefixes = Params.get(params, :ddl_prefixes, __MODULE__)
    node_local_patterns = Params.get(params, :node_local_patterns, __MODULE__)
    ast = Credo.Code.ast(source_file)
    scopes = ReplicatedExecuteScope.line_ranges(ast)

    ast
    |> Macro.prewalk([], fn node, issues ->
      traverse(node, issues, issue_meta, scopes, ddl_prefixes, node_local_patterns)
    end)
    |> elem(1)
    |> Enum.reverse()
  end

  defp traverse(
         {:execute, meta, [argument | _]} = ast,
         issues,
         issue_meta,
         scopes,
         ddl_prefixes,
         node_local_patterns
       ) do
    with sql when is_binary(sql) <- leading_sql(argument),
         true <- ddl?(sql, ddl_prefixes),
         false <- node_local?(sql, node_local_patterns),
         false <- ReplicatedExecuteScope.within?(scopes, meta[:line]) do
      {ast, [issue_for(issue_meta, meta, sql) | issues]}
    else
      _ -> {ast, issues}
    end
  end

  defp traverse(ast, issues, _issue_meta, _scopes, _ddl_prefixes, _node_local_patterns),
    do: {ast, issues}

  defp leading_sql(sql) when is_binary(sql), do: sql
  defp leading_sql({:<<>>, _meta, [sql | _rest]}) when is_binary(sql), do: sql
  defp leading_sql(_argument), do: nil

  defp ddl?(sql, ddl_prefixes) do
    normalized = normalize(sql)

    Enum.any?(ddl_prefixes, &String.starts_with?(normalized, &1 <> " "))
  end

  defp node_local?(sql, node_local_patterns) do
    normalized = normalize(sql)

    Enum.any?(node_local_patterns, &String.contains?(normalized, &1))
  end

  defp normalize(sql) do
    sql
    |> String.trim()
    |> String.downcase()
    |> String.replace(~r/\s+/, " ")
  end

  defp issue_for(issue_meta, meta, sql) do
    format_issue(
      issue_meta,
      message:
        "Wrap `#{sql |> String.trim() |> String.slice(0, 40)}` in Logflare.Repo.Migrator.with_replicated_execute/1 so it is replicated to pglogical subscribers.",
      line_no: meta[:line],
      column: meta[:column]
    )
  end
end
