[
  {"lib/logflare/alerting.ex", "Function application with args (_ :: :ok) will not succeed."},
  {"lib/logflare/alerting.ex", "The pattern can never match the type :ok."},
  {"lib/logflare/alerting.ex", "Function upsert_alert_job/1 has no local return."},
  {"lib/logflare/alerting.ex", "Function create_alert_job_struct/1 has no local return."},
  {"lib/logflare/alerting.ex", "The function call set_name will not succeed."},
  {"lib/logflare/alerting.ex", "The created anonymous function has no local return."},
  {"lib/logflare/alerting.ex", "Function run_alert/1 has no local return."},
  {"lib/logflare/alerting.ex", "Function send_webhook_notification/2 will never be called."},
  {"lib/logflare/alerting.ex", "Function send_slack_notification!/2 will never be called."},
  {"lib/logflare/alerting.ex", "Function execute_alert_query/1 has no local return."},
  {"lib/logflare/alerting.ex", "Function execute_alert_query/2 has no local return."},
  {"lib/logflare/alerting.ex", "Unknown type: Citrine.Job.t/0."},
  {"lib/logflare/alerting/alert_query.ex",
   "Function application with args (_ :: [any()]) will not succeed."},
  {"lib/logflare/application.ex",
   "The pattern variable _goth_child_spec@1 can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/auth.ex", "Unknown type: Logflare.Partners.Partner.t/0."},
  {"lib/logflare/auth/cache.ex", "Unknown type: OauthAccessToken.t/0."},
  {"lib/logflare/auth/cache.ex", "Unknown type: User.t/0."},
  {"lib/logflare/backends.ex", "The function call add_to_table will not succeed."},
  {"lib/logflare/backends.ex", "The created anonymous function has no local return."},
  {"lib/logflare/backends.ex",
   "The pattern can never match the type {:error, :already_started}."},
  {"lib/logflare/backends.ex",
   "The pattern pattern _err@1 = {'error', _} can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/backends.ex",
   "Invalid type specification for function cache_local_buffer_lens."},
  {"lib/logflare/backends.ex", "The function call cache_local_buffer_lens will not succeed."},
  {"lib/logflare/backends.ex", "Function cache_local_buffer_lens/1 has no local return."},
  {"lib/logflare/backends.ex",
   "Invalid type specification for function cached_local_pending_buffer_len."},
  {"lib/logflare/backends.ex", "The function call fetch_events will not succeed."},
  {"lib/logflare/backends.ex", "The pattern can never match the type :drop | :invalid, map()."},
  {"lib/logflare/backends.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor.ex", "Unknown type: AlertQuery.t/0."},
  {"lib/logflare/backends/adaptor/bigquery_adaptor.ex",
   "The function call list_managed_service_accounts will not succeed."},
  {"lib/logflare/backends/adaptor/bigquery_adaptor.ex",
   "Function list_managed_service_accounts/0 has no local return."},
  {"lib/logflare/backends/adaptor/bigquery_adaptor.ex",
   "Invalid type specification for function create_managed_service_accounts."},
  {"lib/logflare/backends/adaptor/bigquery_adaptor.ex",
   "Invalid type specification for function goth_child_spec."},
  {"lib/logflare/backends/adaptor/bigquery_adaptor.ex",
   "Function append_managed_service_accounts/2 has no local return."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor.ex",
   "Invalid type specification for function execute_ch_read_query."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor.ex",
   "The clause guard pattern {'error', _reason@1} cannot succeed."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor.ex",
   "Function insert_log_event/3 has no local return."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor.ex",
   "The function call insert_log_events will not succeed."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor/connection_manager.ex",
   "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor/clickhouse_adaptor/provisioner.ex",
   "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor/loki_adaptor.ex",
   "The created anonymous function has no local return."},
  {"lib/logflare/backends/adaptor/loki_adaptor.ex",
   "The function call to_flatmap will not succeed."},
  {"lib/logflare/backends/adaptor/postgres_adaptor.ex",
   "Type mismatch with behaviour callback to execute_query/2."},
  {"lib/logflare/backends/adaptor/postgres_adaptor.ex", "Unknown type: Source.t/0."},
  {"lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex",
   "Unknown type: Adaptor.source_backend/0."},
  {"lib/logflare/backends/adaptor/postgres_adaptor/pg_repo.ex",
   "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor/postgres_adaptor/shared_repo.ex",
   "Invalid type specification for function down!."},
  {"lib/logflare/backends/adaptor/postgres_adaptor/shared_repo.ex",
   "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/adaptor/s3_adaptor.ex",
   "The function call get_backend will not succeed."},
  {"lib/logflare/backends/adaptor/s3_adaptor.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/backend.ex", "Unknown type: Logflare.Ecto.EncryptedMap.t/0."},
  {"lib/logflare/backends/backend.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/buffer_producer.ex",
   "The pattern can never match the type {:error, :not_initialized}."},
  {"lib/logflare/backends/ingest_event_queue.ex",
   "Invalid type specification for function upsert_tid."},
  {"lib/logflare/backends/ingest_event_queue.ex",
   "Attempted to pattern match against the internal structure of an opaque term of type :ets.tid()."},
  {"lib/logflare/backends/ingest_event_queue.ex", "The pattern can never match the type :ok."},
  {"lib/logflare/backends/ingest_event_queue.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/ingest_event_queue/broadcast_worker.ex",
   "Function local_broadcast_cluster_length/1 has no local return."},
  {"lib/logflare/backends/source_backend.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/backends/source_sup.ex", "Function init/1 has no local return."},
  {"lib/logflare/backends/source_sup.ex",
   "The function call get_default_backend will not succeed."},
  {"lib/logflare/backends/source_sup.ex",
   "Invalid type specification for function start_rule_child."},
  {"lib/logflare/backends/source_sup.ex",
   "Invalid type specification for function stop_rule_child."},
  {"lib/logflare/backends/source_sup.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/billing.ex", "Function sync_payment_methods/1 has no local return."},
  {"lib/logflare/billing.ex", "Unknown type: Logflare.Billing.Plan.t/0."},
  {"lib/logflare/billing/billing_counts.ex", "Unknown type: Timex.Parse.DateTime.t/0."},
  {"lib/logflare/billing/billing_counts.ex", "Unknown type: Logflare.Billing.BillingCount.t/0."},
  {"lib/logflare/billing/stripe.ex",
   "Function create_add_credit_card_session/1 has no local return."},
  {"lib/logflare/billing/stripe.ex", "The function call create will not succeed."},
  {"lib/logflare/billing/stripe.ex", "Function create_payment_session/2 has no local return."},
  {"lib/logflare/billing/stripe.ex", "Function create_customer_session/2 has no local return."},
  {"lib/logflare/billing/stripe.ex",
   "Function create_metered_customer_session/2 has no local return."},
  {"lib/logflare/billing/stripe.ex", "Function change_subscription/3 has no local return."},
  {"lib/logflare/billing/stripe.ex",
   "Function change_from_metered_subscription/3 has no local return."},
  {"lib/logflare/billing/stripe.ex",
   "Function change_to_metered_subscription/3 has no local return."},
  {"lib/logflare/billing/stripe.ex",
   "Function change_metered_to_standard_subscription/3 has no local return."},
  {"lib/logflare/billing/stripe.ex", "Function list_payment_methods/1 has no local return."},
  {"lib/logflare/billing/stripe.ex", "The function call list will not succeed."},
  {"lib/logflare/context_cache/cache_buster.ex", "The pattern can never match the type 
  :noop
  | {Logflare.Auth
     | Logflare.Backends
     | Logflare.Billing
     | Logflare.Endpoints
     | Logflare.SourceSchemas
     | Logflare.Sources
     | Logflare.TeamUsers
     | Logflare.Users, :not_found | integer()}
."},
  {"lib/logflare/context_cache/cache_buster.ex", "Unknown type: Logger.levels/0."},
  {"lib/logflare/context_cache/supervisor.ex", "The pattern can never match the type :dev."},
  {"lib/logflare/context_cache/supervisor.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/context_cache/transaction_broadcaster.ex", "Unknown type: Logger.levels/0."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex",
   "Function query_with_sql_and_params/4 has no local return."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex",
   "Function query_with_sql_and_params/5 has no local return."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex",
   "The function call get_plan_by_user will not succeed."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex", "Function query/3 has no local return."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex", "Function query/4 has no local return."},
  {"lib/logflare/ecto/bigquery/bq_repo.ex",
   "Function warn_if_cost_above_limit/3 will never be called."},
  {"lib/logflare/ecto/ecto_lql_rules_t.ex", "Unknown type: ArgumentError.t/0."},
  {"lib/logflare/ecto/ecto_term_t.ex", "Unknown type: ArgumentError.t/0."},
  {"lib/logflare/endpoints.ex", "Function get_mapped_query_by_token/1 has no local return."},
  {"lib/logflare/endpoints.ex",
   "The pattern can never match the type {:ok, %{:rows => [any()]}}."},
  {"lib/logflare/endpoints.ex",
   "The pattern variable _ can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/endpoints.ex", "Function run_query_string/2 has no local return."},
  {"lib/logflare/endpoints.ex", "Function run_query_string/3 has no local return."},
  {"lib/logflare/endpoints.ex", "The function call run_query will not succeed."},
  {"lib/logflare/endpoints.ex", "Unknown type: Logflare.Alerting.Alert.t/0."},
  {"lib/logflare/endpoints/query.ex", "The pattern can never match the type {:ok, binary()}."},
  {"lib/logflare/endpoints/query.ex", "Function map_query_sources/1 has no local return."},
  {"lib/logflare/google/bigquery/bigquery.ex", "Function init_table!/6 has no local return."},
  {"lib/logflare/google/bigquery/bigquery.ex", "Function create_dataset/3 has no local return."},
  {"lib/logflare/google/bigquery/bigquery.ex", "Function create_dataset/4 has no local return."},
  {"lib/logflare/google/bigquery/bigquery.ex",
   "The function call get_plan_by_user will not succeed."},
  {"lib/logflare/google/bigquery/bigquery.ex",
   "Function patch_dataset_labels/1 has no local return."},
  {"lib/logflare/google/cloud_resource_manager.ex",
   "The function call contains_managed_service_accounts? will not succeed."},
  {"lib/logflare/google/cloud_resource_manager.ex", "The pattern can never match the type 
  {:enabled?, false}
  | {:error,
     :no_project_id
     | %Tesla.Env{
         :__client__ => map(),
         :__module__ => atom(),
         :body => _,
         :headers => [any()],
         :method => :delete | :get | :head | :options | :patch | :post | :put | :trace,
         :opts => [any()],
         :query => [any()],
         :status => nil | integer(),
         :url => binary()
       }}
."},
  {"lib/logflare/google/cloud_resource_manager.ex",
   "Function contains_managed_service_accounts?/1 has no local return."},
  {"lib/logflare/google/cloud_resource_manager.ex",
   "The pattern can never match the type %Tesla.Env{
  :body => _,
  :__client__ => %Tesla.Client{
    :adapter => nil | {_, _} | {_, _, _},
    :fun => _,
    :post => [any()],
    :pre => [any()]
  },
  :__module__ => atom(),
  :auditConfigs => [map()],
  :bindings => [map()],
  :etag => binary(),
  :headers => [{_, _}],
  :method => :delete | :get | :head | :options | :patch | :post | :put | :trace,
  :opts => [{_, _}],
  :query => [{_, _}],
  :status => nil | integer(),
  :url => binary(),
  :version => integer()
}."},
  {"lib/logflare/google/cloud_resource_manager.ex",
   "Function append_managed_service_accounts/2 has no local return."},
  {"lib/logflare/google/cloud_resource_manager.ex",
   "The pattern pattern {'error', _err@1} can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/logs/log_event.ex", "Unknown type: Ecto.UUID.Atom.t/0."},
  {"lib/logflare/logs/log_event.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/logs/log_events.ex", "Function fetch_event_by_id/3 has no local return."},
  {"lib/logflare/logs/log_events_cache.ex", "Function fetch_event_by_id/2 has no local return."},
  {"lib/logflare/logs/log_events_cache.ex", "The function call apply_fun will not succeed."},
  {"lib/logflare/logs/log_events_cache.ex", "Function fetch_event_by_id/3 has no local return."},
  {"lib/logflare/logs/log_events_cache.ex", "Invalid type specification for function get."},
  {"lib/logflare/logs/logs.ex", "Function ingest/1 has no local return."},
  {"lib/logflare/logs/logs.ex", "The function call add_to_table will not succeed."},
  {"lib/logflare/logs/logs.ex",
   "The pattern can never match the type {:drop, _} | {:valid, _} | map()."},
  {"lib/logflare/logs/logs.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/logs/logs_search.ex", "The created anonymous function has no local return."},
  {"lib/logflare/logs/logs_search.ex",
   "Function search_result_aggregates/1 has no local return."},
  {"lib/logflare/logs/logs_search.ex",
   "The function call apply_halt_conditions will not succeed."},
  {"lib/logflare/logs/logs_search.ex",
   "Function query_source_streaming_buffer/1 has no local return."},
  {"lib/logflare/logs/processor.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/logs/rejected_log_events.ex",
   "The pattern variable _other@1 can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/logs/rejected_log_events.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/logs/search_operation.ex", "Unknown type: Source.t/0."},
  {"lib/logflare/logs/search_operations.ex", "Function do_query/1 has no local return."},
  {"lib/logflare/logs/search_operations.ex",
   "The function call where_timestamp_ago will not succeed."},
  {"lib/logflare/logs/search_operations/helpers.ex", "Unknown type: SO.chart_period/0."},
  {"lib/logflare/logs/validators/eq_deep_field_types_validator.ex",
   "The created anonymous function has no local return."},
  {"lib/logflare/logs/validators/eq_deep_field_types_validator.ex",
   "The function call deep_merge will not succeed."},
  {"lib/logflare/lql.ex", "Unknown type: Ecto.Query.DynamicExpr.t/0."},
  {"lib/logflare/lql/backend_transformer.ex", "Unknown type: Logflare.Sources.Source.t/0."},
  {"lib/logflare/lql/backend_transformer/bigquery.ex",
   "Unknown type: Ecto.Query.DynamicExpr.t/0."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__210/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__211/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__212/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__213/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__214/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__215/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__216/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__217/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__224/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__225/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__226/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__227/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__228/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__229/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__23/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__230/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__231/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__232/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__24/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__25/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__26/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__27/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__28/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__29/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__30/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__31/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__628/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__629/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__630/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__631/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__632/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__633/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__634/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__635/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__636/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__681/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__682/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__683/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__684/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__685/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__686/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__687/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__688/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__695/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__696/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__697/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__698/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__699/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__700/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__701/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__702/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__703/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__76/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__77/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__78/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__79/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__80/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__81/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__815/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__816/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__817/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__818/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__819/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__82/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__820/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__821/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__822/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__829/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__83/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__830/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__831/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__832/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__833/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__834/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__835/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__836/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__837/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__90/6 has no local return."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__91/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__92/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__93/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__94/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__95/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__96/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__97/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "Function do_parse__98/6 will never be called."},
  {"lib/logflare/lql/parser.ex", "The pattern can never match the type 
  {:error, <<_::7528>>, binary(), map(), {pos_integer(), non_neg_integer()},
   non_neg_integer()}
."},
  {"lib/logflare/lql/rules/chart_rule.ex", "Unknown type: Ecto.Atom.t/0."},
  {"lib/logflare/lql/rules/filter_rule.ex", "Unknown type: Ecto.Atom.t/0."},
  {"lib/logflare/oauth_access_tokens/partner_oauth_access_token.ex",
   "Unknown type: Logflare.Partners.Partner.t/0."},
  {"lib/logflare/oauth_applications/partner_oauth_application.ex",
   "Unknown type: Logflare.Partners.Partner.t/0."},
  {"lib/logflare/partners.ex", "Unknown type: Logflare.Partners.Partner.t/0."},
  {"lib/logflare/pubsub_rates/cache.ex", "Invalid type specification for function get_buffers."},
  {"lib/logflare/pubsub_rates/cache.ex",
   "The function call get_cluster_buffers will not succeed."},
  {"lib/logflare/pubsub_rates/cache.ex", "Function get_cluster_buffers/1 has no local return."},
  {"lib/logflare/rules.ex", "The function call start_rule_child will not succeed."},
  {"lib/logflare/rules.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/rules/rule.ex", "Unknown type: Ecto.LqlRules.t/0."},
  {"lib/logflare/rules/rule.ex", "Unknown type: Ecto.UUID.Atom.t/0."},
  {"lib/logflare/rules/rule.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/saved_searches/saved_search.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/saved_searches/saved_searches.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/single_tenant.ex", "Unknown type: Logflare.Billing.Plan.t/0."},
  {"lib/logflare/single_tenant.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/source/bigquery/schema.ex", "Invalid type specification for function update."},
  {"lib/logflare/source/bigquery/schema_builder.ex",
   "Function build_table_schema/2 has no local return."},
  {"lib/logflare/source/bigquery/schema_builder.ex",
   "The function call deep_sort_by_fields_name will not succeed."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function test_post/1 has no local return."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function fetch_events/2 has no local return."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function fetch_events/3 has no local return."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function handle_response/2 will never be called."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function take_events/2 will never be called."},
  {"lib/logflare/source/slack_hook_server/slack_hook_server.ex",
   "Function prep_tesla_resp_for_log/1 will never be called."},
  {"lib/logflare/source/supervisor.ex", "The pattern can never match the type {:ok, pid()}."},
  {"lib/logflare/source/supervisor.ex",
   "The pattern pattern _err@1 = {'error', __reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/logflare/source/supervisor.ex",
   "The pattern can never match the type :ignore | {:error, _} | {:ok, pid(), _}."},
  {"lib/logflare/source/supervisor.ex",
   "Invalid type specification for function ensure_started."},
  {"lib/logflare/source/supervisor.ex", "The created anonymous function has no local return."},
  {"lib/logflare/source/supervisor.ex",
   "The pattern can never match the type %Logflare.Source{:v2_pipeline => true, _ => _}."},
  {"lib/logflare/source/v1_source_sup.ex", "Function init/1 has no local return."},
  {"lib/logflare/source/v1_source_sup.ex",
   "The function call get_default_backend will not succeed."},
  {"lib/logflare/source/webhook_notification_server/webhook_notification_server.ex",
   "Function post/4 will never be called."},
  {"lib/logflare/sources.ex", "Function preload_defaults/1 has no local return."},
  {"lib/logflare/sources.ex", "The function call put_bq_table_id will not succeed."},
  {"lib/logflare/sources.ex", "The clause guard pattern {_a@1, _b@1} cannot succeed."},
  {"lib/logflare/sources.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/sources.ex", "Unknown type: Stringt.t/0."},
  {"lib/logflare/sources.ex", "Unknown type: Logflare.Billing.Plan.t/0."},
  {"lib/logflare/sources/counters.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/sources/source_routing.ex", "The function call get_backend will not succeed."},
  {"lib/logflare/sources/source_routing.ex",
   "The function call start_rule_child will not succeed."},
  {"lib/logflare/sql.ex", "Invalid type specification for function source_mapping."},
  {"lib/logflare/sql.ex", "Invalid type specification for function parameter_positions."},
  {"lib/logflare/sql.ex", "Function translate/3 has no local return."},
  {"lib/logflare/sql.ex", "Function translate/4 has no local return."},
  {"lib/logflare/sql.ex", "Unknown type: Logflare.Alerts.Alert.t/0."},
  {"lib/logflare/sql/dialect_transformer.ex", "Unknown type: Logflare.Sources.Source.t/0."},
  {"lib/logflare/sql/dialect_translation.ex",
   "Function translate_bq_to_pg/1 has no local return."},
  {"lib/logflare/sql/dialect_translation.ex",
   "Function translate_bq_to_pg/2 has no local return."},
  {"lib/logflare/sql/dialect_translation.ex",
   "The created anonymous function has no local return."},
  {"lib/logflare/sql/dialect_translation.ex", "The pattern can never match the type binary()."},
  {"lib/logflare/sql/dialect_translation.ex",
   "Function bq_to_pg_convert_parameters/2 will never be called."},
  {"lib/logflare/sql/dialect_translation.ex",
   "Function do_parameter_positions_mapping/2 will never be called."},
  {"lib/logflare/system_metrics/cachex/poller.ex",
   "The pattern can never match the type {:error, map()}."},
  {"lib/logflare/user.ex", "Unknown type: Logflare.Billing.BillingCount.t/0."},
  {"lib/logflare/user.ex", "Unknown type: Logflare.Partners.Partner.t/0."},
  {"lib/logflare/user.ex", "Unknown type: Logflare.Source.t/0."},
  {"lib/logflare/user.ex", "Unknown type: Logflare.Vercel.Auth.t/0."},
  {"lib/logflare/user.ex", "Function preferences_changeset/2 has no local return."},
  {"lib/logflare/user.ex", "The function call cast_embed will not succeed."},
  {"lib/logflare/user.ex", "The created anonymous function has no local return."},
  {"lib/logflare/users/api.ex", "Function verify_api_rates_quotas/1 has no local return."},
  {"lib/logflare/users/api.ex", "Function get_total_user_api_rate/1 has no local return."},
  {"lib/logflare/users/api.ex", "The function call preload_sources will not succeed."},
  {"lib/logflare/utils.ex",
   "List construction (cons) will produce an improper list, because its second argument is map()."},
  {"lib/logflare_grpc/google/rpc/context/attribute_context.pb.ex",
   "Unknown type: Google.Protobuf.Struct.t/0."},
  {"lib/logflare_grpc/google/rpc/context/attribute_context.pb.ex",
   "Unknown type: Google.Protobuf.Timestamp.t/0."},
  {"lib/logflare_grpc/google/rpc/context/attribute_context.pb.ex",
   "Unknown type: Google.Protobuf.Duration.t/0."},
  {"lib/logflare_grpc/google/rpc/context/attribute_context.pb.ex",
   "Unknown type: Google.Protobuf.Any.t/0."},
  {"lib/logflare_grpc/google/rpc/context/audit_context.pb.ex",
   "Unknown type: Google.Protobuf.Struct.t/0."},
  {"lib/logflare_grpc/google/rpc/error_details.pb.ex",
   "Unknown type: Google.Protobuf.Duration.t/0."},
  {"lib/logflare_grpc/google/rpc/status.pb.ex", "Unknown type: Google.Protobuf.Any.t/0."},
  {"lib/logflare_web/controllers/api/access_token_controller.ex",
   "Function application with args (
  _ ::
    {:error,
     %Ecto.Changeset{
       :action => atom(),
       :changes => %{atom() => _},
       :constraints => [map()],
       :data => nil | map(),
       :empty_values => _,
       :errors => [{_, _}],
       :filters => %{atom() => _},
       :params => nil | %{binary() => _},
       :prepare => [(_ -> any())],
       :repo => atom(),
       :repo_opts => [{_, _}],
       :required => [atom()],
       :types => %{atom() => atom() | {_, _}},
       :valid? => boolean(),
       :validations => [{_, _}]
     }}
) will not succeed."},
  {"lib/logflare_web/controllers/billing_controller.ex",
   "Function env_stripe_publishable_key/0 will never be called."},
  {"lib/logflare_web/controllers/billing_controller.ex",
   "The pattern variable _err@1 can never match the type, because it is covered by previous clauses."},
  {"lib/logflare_web/controllers/endpoints_controller.ex",
   "Function query/2 has no local return."},
  {"lib/logflare_web/controllers/endpoints_controller.ex", "The guard clause can never succeed."},
  {"lib/logflare_web/controllers/health_check_controller.ex",
   "The pattern can never match the type {:error, number()}."},
  {"lib/logflare_web/controllers/plugs/fetch_resource.ex", "The guard clause can never succeed."},
  {"lib/logflare_web/controllers/plugs/rate_limiter.ex", "Function call/1 has no local return."},
  {"lib/logflare_web/controllers/plugs/rate_limiter.ex", "Function call/2 has no local return."},
  {"lib/logflare_web/controllers/plugs/set_plan_from_cache.ex",
   "The function call get_plan_by_user will not succeed."},
  {"lib/logflare_web/controllers/plugs/verify_api_access.ex",
   "The function call get_user_by_uuid will not succeed."},
  {"lib/logflare_web/controllers/plugs/verify_api_access.ex",
   "The function call identify_requestor will not succeed."},
  {"lib/logflare_web/controllers/saved_searches.ex", "The pattern can never match the type 
  {:ok,
   %Logflare.SavedSearch{
     :__meta__ => %Ecto.Schema.Metadata{
       :context => _,
       :prefix => _,
       :schema => atom(),
       :source => binary(),
       :state => :built | :deleted | :loaded
     },
     :id => nil | integer(),
     :inserted_at =>
       nil
       | %NaiveDateTime{
           :calendar => atom(),
           :day => pos_integer(),
           :hour => non_neg_integer(),
           :microsecond => {non_neg_integer(), non_neg_integer()},
           :minute => non_neg_integer(),
           :month => pos_integer(),
           :second => non_neg_integer(),
           :year => integer()
         },
     :lql_charts => nil | [map()],
     :lql_filters => nil | [map()],
     :querystring => nil | binary(),
     :saved_by_user => false | nil | true,
     :source => _,
     :source_id => nil | integer(),
     :tailing => false | nil | true,
     :updated_at =>
       nil
       | %NaiveDateTime{
           :calendar => atom(),
           :day => pos_integer(),
           :hour => non_neg_integer(),
           :microsecond => {non_neg_integer(), non_neg_integer()},
           :minute => non_neg_integer(),
           :month => pos_integer(),
           :second => non_neg_integer(),
           :year => integer()
         }
   }}
."},
  {"lib/logflare_web/controllers/source_controller.ex",
   "The created anonymous function has no local return."},
  {"lib/logflare_web/controllers/source_controller.ex",
   "The function call via_source will not succeed."},
  {"lib/logflare_web/controllers/source_controller.ex",
   "Function test_alerts/2 has no local return."},
  {"lib/logflare_web/controllers/source_controller.ex",
   "Function test_slack_hook/2 has no local return."},
  {"lib/logflare_web/controllers/stripe_controller.ex",
   "The pattern can never match the type %Logflare.Billing.PaymentMethod{
  :__meta__ => %Ecto.Schema.Metadata{
    :context => _,
    :prefix => _,
    :schema => atom(),
    :source => binary(),
    :state => :built | :deleted | :loaded
  },
  :brand => nil | binary(),
  :customer_id => nil | binary(),
  :exp_month => nil | integer(),
  :exp_year => nil | integer(),
  :id => nil | integer(),
  :inserted_at =>
    nil
    | %NaiveDateTime{
        :calendar => atom(),
        :day => pos_integer(),
        :hour => non_neg_integer(),
        :microsecond => {non_neg_integer(), non_neg_integer()},
        :minute => non_neg_integer(),
        :month => pos_integer(),
        :second => non_neg_integer(),
        :year => integer()
      },
  :last_four => nil | binary(),
  :price_id => nil | binary(),
  :stripe_id => nil | binary(),
  :updated_at =>
    nil
    | %NaiveDateTime{
        :calendar => atom(),
        :day => pos_integer(),
        :hour => non_neg_integer(),
        :microsecond => {non_neg_integer(), non_neg_integer()},
        :minute => non_neg_integer(),
        :month => pos_integer(),
        :second => non_neg_integer(),
        :year => integer()
      }
}."},
  {"lib/logflare_web/controllers/stripe_controller.ex",
   "The pattern variable _err@4 can never match the type, because it is covered by previous clauses."},
  {"lib/logflare_web/controllers/stripe_controller.ex", "The pattern can never match the type 
  {:error,
   %Ecto.Changeset{
     :action => atom(),
     :changes => map(),
     :constraints => [any()],
     :data => nil | map(),
     :empty_values => _,
     :errors => [any()],
     :filters => map(),
     :params => nil | map(),
     :prepare => [any()],
     :repo => atom(),
     :repo_opts => [any()],
     :required => [any()],
     :types => map(),
     :valid? => boolean(),
     :validations => [any()]
   }}
."},
  {"lib/logflare_web/live/backends/backends_live.ex",
   "The function call preload_rules will not succeed."},
  {"lib/logflare_web/live/billingaccount_live/payment_method_component.ex",
   "The pattern variable __err@1 can never match the type, because it is covered by previous clauses."},
  {"lib/logflare_web/live/billingaccount_live/payment_method_component.ex",
   "The function call update_customer will not succeed."},
  {"lib/logflare_web/live/monaco_editor_component.ex",
   "The pattern can never match the type true."},
  {"lib/logflare_web/live/query_live.ex", "The pattern can never match the type true."},
  {"lib/logflare_web/live/query_live.ex", "Function run_query/3 has no local return."},
  {"lib/logflare_web/live/search_live/logs_search_lv.ex", "The pattern can never match the type 
  {:ok,
   %Logflare.SavedSearch{
     :__meta__ => %Ecto.Schema.Metadata{
       :context => _,
       :prefix => _,
       :schema => atom(),
       :source => binary(),
       :state => :built | :deleted | :loaded
     },
     :id => nil | integer(),
     :inserted_at =>
       nil
       | %NaiveDateTime{
           :calendar => atom(),
           :day => pos_integer(),
           :hour => non_neg_integer(),
           :microsecond => {non_neg_integer(), non_neg_integer()},
           :minute => non_neg_integer(),
           :month => pos_integer(),
           :second => non_neg_integer(),
           :year => integer()
         },
     :lql_charts => nil | [map()],
     :lql_filters => nil | [map()],
     :querystring => nil | binary(),
     :saved_by_user => false | nil | true,
     :source => _,
     :source_id => nil | integer(),
     :tailing => false | nil | true,
     :updated_at =>
       nil
       | %NaiveDateTime{
           :calendar => atom(),
           :day => pos_integer(),
           :hour => non_neg_integer(),
           :microsecond => {non_neg_integer(), non_neg_integer()},
           :minute => non_neg_integer(),
           :month => pos_integer(),
           :second => non_neg_integer(),
           :year => integer()
         }
   }}
."},
  {"lib/logflare_web/live/search_live/logs_search_lv.ex",
   "The function call diff will not succeed."},
  {"lib/logflare_web/live/search_live/logs_search_lv.ex",
   "The created anonymous function has no local return."},
  {"lib/logflare_web/templates/phoenix_oauth2_provider/application/form.html.eex",
   "The test binary() == nil can never evaluate to 'true'."},
  {"lib/logflare_web/views/source_view.ex",
   "Attempted to pattern match against the internal structure of an opaque term of type URI.authority()."},
  {"lib/telemetry.ex", "Function metrics/0 has no local return."},
  {"test/support/test_utils.ex", "Function build_bq_schema/1 has no local return."},
  {"test/support/test_utils_grpc.ex", "The pattern can never match the type 
  :array_of_booleans
  | :array_of_doubles
  | :array_of_integers
  | :array_of_strings
  | :boolean
  | :double
  | :integer
  | :string
."}
]
