services:
  logflare:
    environment:
     POSTGRES_BACKEND_URL: postgresql://postgres:postgres@localhost:5432/logflare_dev
    volumes: !override
      - type: bind
        source: ${PWD}/.single_tenant_pg.env
        target: /tmp/.secrets.env
        read_only: true
