FROM supabase/logflare:base AS builder

ENV MIX_ENV=prod

WORKDIR /app

COPY ./VERSION mix.exs mix.lock ./
COPY config/config.exs config/
COPY config/prod.exs config/
COPY config/runtime.exs config/
RUN mix do deps.get + deps.compile

COPY . ./

# release
RUN mix release  && \
    npm run --prefix assets deploy && \
    mix phx.digest

FROM supabase/logflare:runner

# Only the self-contained release is needed at runtime, not the rest of _build.
COPY --from=builder /app/_build/prod/rel/logflare /opt/app/rel/logflare
COPY --from=builder /app/VERSION /opt/app/VERSION
COPY --from=builder /app/priv/static /opt/app/rel/logflare/bin/priv/static

# Move files to the correct folder taking into consideration the VERSION
RUN cp -r /opt/app/rel/logflare/bin/priv/static /opt/app/rel/logflare/lib/logflare-$(cat /opt/app/VERSION)/priv/static

# Cleanup static assets not in use
RUN rm -r /opt/app/rel/logflare/bin/priv

WORKDIR /opt/app/rel/logflare/bin
COPY run.sh ./run.sh
CMD ["sh", "run.sh"]
