apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logflare.fullname" . }}
  labels:
    {{- include "logflare.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.logflare.secrets.publicAccessToken.existingSecret }}
  LOGFLARE_PUBLIC_ACCESS_TOKEN: {{ .Values.logflare.secrets.publicAccessToken.value | quote }}
  {{- end }}
  {{- if not .Values.logflare.secrets.privateAccessToken.existingSecret }}
  LOGFLARE_PRIVATE_ACCESS_TOKEN: {{ .Values.logflare.secrets.privateAccessToken.value | quote }}
  {{- end }}
  {{- if not .Values.logflare.secrets.dbPassword.existingSecret }}
  DB_PASSWORD: {{ .Values.logflare.secrets.dbPassword.value | quote }}
  {{- end }}
  {{- if not .Values.logflare.secrets.dbEncryptionKey.existingSecret }}
  LOGFLARE_DB_ENCRYPTION_KEY: {{ .Values.logflare.secrets.dbEncryptionKey.value | quote }}
  {{- end }}
  {{- if not .Values.logflare.secrets.phxSecretKeyBase.existingSecret }}
  PHX_SECRET_KEY_BASE: {{ .Values.logflare.secrets.phxSecretKeyBase.value | quote }}
  {{- end }}
  {{- if not .Values.logflare.secrets.phxLiveViewSigningSalt.existingSecret }}
  PHX_LIVE_VIEW_SIGNING_SALT: {{ .Values.logflare.secrets.phxLiveViewSigningSalt.value | quote }}
  {{- end }}
  {{- if eq .Values.logflare.backend.type "postgres" }}
  {{- if not .Values.logflare.secrets.postgresBackendUrl.existingSecret }}
  POSTGRES_BACKEND_URL: {{ .Values.logflare.secrets.postgresBackendUrl.value | quote }}
  {{- end }}
  {{- else if eq .Values.logflare.backend.type "bigquery" }}
  {{- if not .Values.logflare.secrets.googleServiceAccountJson.existingSecret }}
  GOOGLE_SERVICE_ACCOUNT: {{ .Values.logflare.secrets.googleServiceAccountJson.value | quote }}
  {{- end }}
  {{- end }}
