apiVersion: v1
kind: Service
metadata:
  name: {{ include "logflare.fullname" . }}
  labels:
    {{- include "logflare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "logflare.servicePorts" . | nindent 4 }}
  selector:
    {{- include "logflare.selectorLabels" . | nindent 4 }}
