import { test, expect } from '@playwright/test';
import { searchLogs } from '../lib/utils';
import supabase from '../lib/supabase';

test.beforeAll(async ({ request }) => {
  await supabase.auth.signUp({ email: 'example@email.com', password: 'example-password' })

  await supabase.storage.createBucket('avatars')
  await supabase.storage.deleteBucket('avatars')

  await supabase.functions.invoke('hello', { body: { name: 'Functions' } })

  // PostgRest
  await request.post('/api/platform/pg-meta/default/query?key=table-create-with-columns', { data: {
    disable_statement_timeout: false,
    query: "BEGIN; CREATE TABLE public.\"table_test\" (); COMMENT ON TABLE public.\"table_test\" IS ''; COMMIT;;\nALTER TABLE \"public\".\"table_test\" ENABLE ROW LEVEL SECURITY;\n\nBEGIN;\n  ALTER TABLE public.\"table_test\" ADD COLUMN id int8\n    GENERATED BY DEFAULT AS IDENTITY\n    \n    \n    \n    ;\n  ;\nCOMMIT;;\n\nBEGIN;\n  ALTER TABLE public.\"table_test\" ADD COLUMN created_at timestamptz\n    DEFAULT now()\n    NOT NULL\n    \n    \n    ;\n  ;\nCOMMIT;;\nALTER TABLE \"public\".\"table_test\" ADD PRIMARY KEY (\"id\")"
  }});

  // Cron jobs
  await request.post('/api/platform/pg-meta/default/query?key=extension-create', { data: {
    disable_statement_timeout: false,
    query: "\nCREATE EXTENSION pg_cron\n  SCHEMA pg_catalog\n  VERSION '1.6'\n  CASCADE;"
  }});

  await request.post('/api/platform/pg-meta/default/query?key=cron-jobs-create', { data: {
    disable_statement_timeout: false,
    query: "select cron.schedule('test_cron', '5 seconds', $$SELECT auth.email()$$);"
  }});

  await new Promise(r => setTimeout(r, 12000))
});

test('receives logs from API Gateway', async ({ page }) => {
  await page.goto('/project/default/logs/edge-logs');
  await searchLogs(page, '/functions/v1/hello');

  await expect(page.getByRole('table')).toContainText('/functions/v1/hello');
});

test('receives logs from PostgREST', async ({ page }) => {
  await page.goto('/project/default/logs/postgrest-logs');
  await searchLogs(page, '12 Relations');

  await expect(page.getByRole('table')).toContainText('Schema cache loaded 12 Relations');
});

test('receives logs from Auth', async ({ page }) => {
  await page.goto('/project/default/logs/auth-logs');
  await searchLogs(page, 'example@email.com');

  await expect(page.getByRole('table')).toContainText('/signup | request completed');
});

test('receives logs from Storage', async ({ page }) => {
  await page.goto('/project/default/logs/storage-logs');
  await searchLogs(page, '/bucket/avatars');

  await expect(page.getByRole('table')).toContainText('/bucket/avatars');
});

test('receives logs from Edge Functions', async ({ page }) => {
  await page.goto('/project/default/logs/edge-functions-logs');

  await expect(page.getByRole('table')).toContainText('serving the request with /home/deno/functions/hello');
});

test('receives logs from Cron', async ({ page }) => {
  await page.goto('/project/default/logs/pgcron-logs');

  await expect(page.getByRole('table')).toContainText('LOG: cron job 1 completed: 1 row');
  await expect(page.getByRole('table')).toContainText('LOG: cron job 1 starting: SELECT auth.email()');
});


