import { test, expect, Page } from '@playwright/test';

test.beforeAll(async ({ request }) => {
  await request.get('/api/platform/organizations');

  await request.post('/api/platform/storage/default/buckets', { data: {id: "bucket", type: "STANDARD", public: false}});
  await request.post('/storage/v1/object/bucket/folder/.emptyFolderPlaceholder');

  await request.post('/api/platform/auth/default/users', { data: {email: "test_user@gmail.com", password: "password", email_confirm: true}});

  await request.post('/functions/v1/hello-world', { data: { name: "Functions" }});

  await request.post('/api/platform/pg-meta/default/query?key=table-create-with-columns', { data: {
    disable_statement_timeout: false,
    query: "BEGIN; CREATE TABLE public.\"table_test\" (); COMMENT ON TABLE public.\"table_test\" IS ''; COMMIT;;\nALTER TABLE \"public\".\"table_test\" ENABLE ROW LEVEL SECURITY;\n\nBEGIN;\n  ALTER TABLE public.\"table_test\" ADD COLUMN id int8\n    GENERATED BY DEFAULT AS IDENTITY\n    \n    \n    \n    ;\n  ;\nCOMMIT;;\n\nBEGIN;\n  ALTER TABLE public.\"table_test\" ADD COLUMN created_at timestamptz\n    DEFAULT now()\n    NOT NULL\n    \n    \n    ;\n  ;\nCOMMIT;;\nALTER TABLE \"public\".\"table_test\" ADD PRIMARY KEY (\"id\")"
  }});

  await new Promise(r => setTimeout(r, 10000))
});

test('receives logs from API Gateway', async ({ page }) => {
  await page.goto('/project/default/logs/edge-logs');
  await searchLogs(page, '/api/platform/organizations');

  await expect(page.getByRole('table')).toContainText('/api/platform/organizations');
});

test('receives logs from Storage', async ({ page }) => {
  await page.goto('/project/default/logs/storage-logs');
  await searchLogs(page, 'folder');

  await expect(page.getByRole('table')).toContainText('/object/bucket/folder/.emptyFolderPlaceholder');
});

test('receives logs from Auth', async ({ page }) => {
  await page.goto('/project/default/logs/auth-logs');
  await searchLogs(page, 'test_user@gmail.com');

  await expect(page.getByRole('table')).toContainText('/admin/users | request completed');
});

test('receives logs from PostgREST', async ({ page }) => {
  await page.goto('/project/default/logs/postgrest-logs');
  await searchLogs(page, '12 Relations');

  await expect(page.getByRole('table')).toContainText('Schema cache loaded 12 Relations');
});

test('receives logs from Edge Functions', async ({ page }) => {
  await page.goto('/project/default/logs/edge-functions-logs');

  await expect(page.getByRole('table')).toContainText('serving the request with /home/deno/functions/hello-world');
});

export async function searchLogs(page: Page, searchText: string): Promise<void> {
  const searchInput = page.locator('input[placeholder="Search events"]');

  await searchInput.fill(searchText);
  await searchInput.press('Enter');
}