import { test, expect } from '@playwright/test';
import { searchLogs } from '../lib/utils';
import supabase from '../lib/supabase';

let uniqueId = '';

test.setTimeout(60_000);
expect.configure({ timeout: 15_000 });

test.beforeAll(async ({ request, browserName }) => {
  test.setTimeout(60_000);

  uniqueId = `${Date.now()}_${browserName}`;

  await supabase.auth.signUp({ email: `example_${uniqueId}@email.com`, password: 'example-password' })

  await supabase.storage.createBucket(`avatars_${uniqueId}`)
  await supabase.storage.deleteBucket(`avatars_${uniqueId}`)

  await supabase.functions.invoke(`function_${uniqueId}`)
  await supabase.functions.invoke('hello')

  // Realtime
  const channel = supabase.channel(`test_${uniqueId}`)
  channel.subscribe()
  await new Promise(r => setTimeout(r, 2000))
  await supabase.removeChannel(channel)

  // PostgRest
  await request.post('/api/platform/pg-meta/default/query?key=table-create-with-columns', { data: {
    disable_statement_timeout: false,
    query: `BEGIN; CREATE TABLE public."table_test_${uniqueId}" (); COMMENT ON TABLE public."table_test_${uniqueId}" IS ''; COMMIT;;\nALTER TABLE "public"."table_test_${uniqueId}" ENABLE ROW LEVEL SECURITY;\n\nBEGIN;\n  ALTER TABLE public."table_test_${uniqueId}" ADD COLUMN id int8\n    GENERATED BY DEFAULT AS IDENTITY\n    \n    \n    \n    ;\n  ;\nCOMMIT;;\n\nBEGIN;\n  ALTER TABLE public."table_test_${uniqueId}" ADD COLUMN created_at timestamptz\n    DEFAULT now()\n    NOT NULL\n    \n    \n    ;\n  ;\nCOMMIT;;\nALTER TABLE "public"."table_test_${uniqueId}" ADD PRIMARY KEY ("id")`
  }});

  // Cron jobs
  await request.post('/api/platform/pg-meta/default/query?key=extension-create', { data: {
    disable_statement_timeout: false,
    query: "\nCREATE EXTENSION IF NOT EXISTS pg_cron\n  SCHEMA pg_catalog\n  VERSION '1.6'\n  CASCADE;"
  }});

  await request.post('/api/platform/pg-meta/default/query?key=cron-jobs-create', { data: {
    disable_statement_timeout: false,
    query: `select cron.schedule('test_cron_${uniqueId}', '5 seconds', $$SELECT auth.email()$$);`
  }});

  await new Promise(r => setTimeout(r, 30_000))
});

test.afterAll(async ({ request }) => {
  await request.post('/api/platform/pg-meta/default/query?key=cron-jobs-unschedule', { data: {
    disable_statement_timeout: false,
    query: `select cron.unschedule('test_cron_${uniqueId}');`
  }});
});

test('receives logs from API Gateway', async ({ page }) => {
  await page.goto('/project/default/logs/edge-logs');
  await searchLogs(page, `/functions/v1/function_${uniqueId}`);

  await expect(page.getByRole('table')).toContainText(`/functions/v1/function_${uniqueId}`);
});

test('receives logs from PostgREST', async ({ page }) => {
  await page.goto('/project/default/logs/postgrest-logs');
  await searchLogs(page, 'Config reloaded');

  await expect(page.getByRole('table')).toContainText('Config reloaded');
});

test('receives logs from Auth', async ({ page }) => {
  await page.goto('/project/default/logs/auth-logs');
  await searchLogs(page, `example_${uniqueId}@email.com`);

  await expect(page.getByRole('table')).toContainText('/signup | request completed');
});

test('receives logs from Storage', async ({ page }) => {
  await page.goto('/project/default/logs/storage-logs');
  await searchLogs(page, `/bucket/avatars_${uniqueId}`);

  await expect(page.getByRole('table')).toContainText(`/bucket/avatars_${uniqueId}`);
});

test('receives logs from Realtime', async ({ page }) => {
  await page.goto('/project/default/logs/realtime-logs');
  await searchLogs(page, 'Billing');

  await expect(page.getByRole('table')).toContainText('Billing metrics');
});

test('receives logs from Edge Functions', async ({ page }) => {
  await page.goto('/project/default/logs/edge-functions-logs');
  await searchLogs(page, '/home/deno/functions/hello');

  await expect(page.getByRole('table')).toContainText('serving the request with /home/deno/functions/hello');
});

test('receives logs from Cron', async ({ page }) => {
  await page.goto('/project/default/logs/pgcron-logs');

  await expect(page.getByRole('table')).toContainText(/LOG:\s+cron job \d+ completed: 1 row/);
  await expect(page.getByRole('table')).toContainText(/LOG:\s+cron job \d+ starting: SELECT auth\.email\(\)/);
});
