steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=gcloud_staging.json.enc
      - --plaintext-file=gcloud.json
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./.staging.env.enc
      - --plaintext-file=./.secrets.env
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./.staging.cert.pem.enc
      - --plaintext-file=./cert.pem
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./.staging.cert.key.enc
      - --plaintext-file=./cert.key
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./.staging.cacert.pem.enc
      - --plaintext-file=./cacert.pem
      - --location=us-central1
      - --keyring=logflare-keyring-us-central1
      - --key=logflare-secrets-key
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "TAG_VERSION=${_IMAGE_TAG}",
        "-f",
        "secret_setup.Dockerfile",
        "-t",
        "${_CONTAINER_IMAGE}",
        "-t",
        "gcr.io/$PROJECT_ID/logflare_app:latest",
        ".",
      ]

substitutions:
    # override this manually with cli as we aren't using cloud trigger anymore
    _ENV: staging
    _IMAGE_TAG: $SHORT_SHA
    _CONTAINER_IMAGE: gcr.io/$PROJECT_ID/logflare_app:${_IMAGE_TAG}

images:
  - "gcr.io/$PROJECT_ID/logflare_app:${_IMAGE_TAG}"
  - "gcr.io/$PROJECT_ID/logflare_app:latest"

timeout: 1800s

options:
    dynamicSubstitutions: true
    substitutionOption: 'ALLOW_LOOSE'