steps:
  # create instance template
  - name: gcr.io/cloud-builders/gcloud
    allowExitCodes: [1]
    args:
      - compute
      - instance-templates
      - create-with-container
      - $_TEMPLATE_NAME
      - --boot-disk-size=25GB
      - --boot-disk-type=pd-balanced
      - --machine-type=${_INSTANCE_TYPE}
      - --project=logflare-staging
      - --network-interface=network=default,network-tier=PREMIUM
      - --maintenance-policy=TERMINATE
      - --service-account=compute-engine-2022@logflare-staging.iam.gserviceaccount.com
      - --scopes=https://www.googleapis.com/auth/cloud-platform
      - --tags=phoenix-http,https-server
      - --container-image=${_CONTAINER_IMAGE}
      - --metadata-from-file=shutdown-script=./cloudbuild/shutdown.sh
      - --metadata-from-file=startup-script=./cloudbuild/startup.sh
      # needed for enabling node-problem-detector, explicitly enable logging
      - --metadata=google-monitoring-enabled=true,google-logging-enabled=true
      - --container-privileged
      - --container-restart-policy=always
      - --container-env=LOGFLARE_GRPC_PORT=4001,RELEASE_COOKIE=${_COOKIE}
      - --no-shielded-secure-boot
      - --shielded-vtpm
      - --shielded-integrity-monitoring
      - --labels=container-vm=cos-stable-109-17800-66-54
  # update instance group to the new template
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - ${_INSTANCE_GROUP}
      - --project=logflare-staging
      - --zone=us-central1-a
      - --type=proactive
      - --max-surge=1
      - --max-unavailable=0
      - --min-ready=300
      - --minimal-action=replace
      - --most-disruptive-allowed-action=replace
      - --replacement-method=substitute
      - --version=template=projects/logflare-staging/global/instanceTemplates/${_TEMPLATE_NAME}

substitutions:
  _CLUSTER: main
  _COOKIE: default-${_CLUSTER}
  _NORMALIZED_IMAGE_TAG: ${_IMAGE_TAG}
  _INSTANCE_TYPE: c2d-standard-2
  _INSTANCE_GROUP: instance-group-staging-${_CLUSTER}
  _IMAGE_TAG: $SHORT_SHA
  _TEMPLATE_NAME: logflare-staging-${_CLUSTER}-cluster-${_NORMALIZED_IMAGE_TAG}
  _CONTAINER_IMAGE: gcr.io/logflare-staging/logflare_app:${_IMAGE_TAG}
timeout: 1800s
options:
  dynamicSubstitutions: true
  substitutionOption: "ALLOW_LOOSE"
