steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - "--ciphertext-file=cloudbuild/.prod.gcloud.json.enc"
      - "--plaintext-file=gcloud.json"
      - "--location=us-central1"
      - "--keyring=logflare-prod-keyring-us-central1"
      - "--key=logflare-prod-secrets-key"
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./cloudbuild/.prod.db-client-cert.pem.enc
      - --plaintext-file=./db-client-cert.pem
      - "--location=us-central1"
      - "--keyring=logflare-prod-keyring-us-central1"
      - "--key=logflare-prod-secrets-key"
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./cloudbuild/.prod.db-client-key.pem.enc
      - --plaintext-file=./db-client-key.pem
      - "--location=us-central1"
      - "--keyring=logflare-prod-keyring-us-central1"
      - "--key=logflare-prod-secrets-key"
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=./cloudbuild/.prod.db-server-ca.pem.enc
      - --plaintext-file=./db-server-ca.pem
      - "--location=us-central1"
      - "--keyring=logflare-prod-keyring-us-central1"
      - "--key=logflare-prod-secrets-key"
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "TAG_VERSION=${_IMAGE_TAG}",
        "-f",
        "cloudbuild/secret_setup.Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/logflare_app:${_IMAGE_TAG}",
        "-t",
        "gcr.io/$PROJECT_ID/logflare_app:latest",
        ".",
      ]

timeout: 1800s

substitutions:
  # override this manually with cli as we aren't using cloud trigger anymore
  _IMAGE_TAG: $SHORT_SHA
  _CONTAINER_IMAGE: gcr.io/${PROJECT_ID}/logflare_app:${_IMAGE_TAG}

images:
  - "gcr.io/${PROJECT_ID}/logflare_app:${_IMAGE_TAG}"
  - "gcr.io/${PROJECT_ID}/logflare_app:latest"

options:
  dynamicSubstitutions: true
  substitutionOption: "ALLOW_LOOSE"
