name: Testing Docker Platforms

on:
  workflow_dispatch:
  pull_request:
    branches: [staging]

permissions:
  contents: read

jobs:
  publish_latest:
    name: Publish latest tagged image
    runs-on: ubuntu-latest
    env:
      PUSH_TO_DOCKER: ${{github.ref == 'refs/heads/staging'}}
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: echo "LOGFLARE_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Get commit SHA
        run: echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Version
        uses: docker/build-push-action@v3
        with:
          push: ${{env.PUSH_TO_DOCKER}}
          tags: supabase/logflare:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64

