name: Docker CI Multi-Platform

on:
  workflow_dispatch:
  push:
    branches: [staging, master]

permissions:
  contents: read

jobs:
  settings:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.env.outputs.version}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup outputs
        id: env
        run: |
          echo "version=$(cat ./VERSION)" >> "$GITHUB_OUTPUT"
  build:
    needs: settings
    strategy:
      matrix:
        include:
          - runner: [self-hosted, X64]
            arch: amd64
          - runner: arm-runner
            arch: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120
    outputs:
      digest_arm64: ${{ steps.build-arm64.outputs.digest }}
      digest_amd64: ${{ steps.build-amd64.outputs.digest }}
    steps:
      # checkout git commit 
      - uses: actions/checkout@v3
      # Setup docker
      # https://github.com/supabase/postgres/blob/develop/.github/workflows/dockerhub-release.yml#LL41C11-L42C44
      - run: docker context create builders
      - uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push
      - id: build-${{ matrix.arch}}
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: supabase/logflare:${{ needs.settings.outputs.version }}-${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          # caching
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge_publish:
    needs:
      - settings
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Merge multi-arch manifests
        run: |
          docker buildx imagetools create -t supabase/logflare:latest \
          supabase/logflare@${{ needs.build.outputs.digest_amd64 }} \
          supabase/logflare@${{ needs.build.outputs.digest_arm64 }}
      - name: master - Tag and push
        if: ${{github.ref == 'refs/heads/master'}}
        run: |
          docker image tag supabase/logflare:latest supabase/logflare:${{ needs.settings.outputs.version }}
          docker image push --all-tags supabase/logflare
      - name: staging - Tag and push
        if: ${{github.ref == 'refs/heads/staging'}}
        run: |
          docker image tag supabase/logflare:latest supabase/logflare:staging
          docker image push supabase/logflare:staging
