name: Docker Build Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'native/**'
      - 'priv/**'
      - 'rel/**'
      - 'config/**'
      - 'assets/**'
      - 'Dockerfile'
      - '!assets/**'
      - '*.sh'
      - '.tool-versions'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: false
          platforms: linux/amd64
          # caching
          cache-from: type=gha
          cache-to: type=gha,mode=max