name: Deploy to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ">=22.9"
          cache: "npm"
          cache-dependency-path: docs/docs.logflare.com/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        working-directory: ./docs/docs.logflare.com
        run: npm ci
      - name: Build
        working-directory: ./docs/docs.logflare.com
        run: npm run build
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/docs.logflare.com/build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
