name: Check pages build

on:
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: ">=22.9"
          cache: npm
          cache-dependency-path: docs/docs.logflare.com/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        working-directory: ./docs/docs.logflare.com
        run: npm ci
      - name: Check build
        working-directory: ./docs/docs.logflare.com
        run: npm run build
