name: Release checks

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      SHELL: /bin/bash
    steps:
      - uses: actions/checkout@v3
      - name: Ensure version changed
        run: |
          git fetch origin master
          git fetch origin staging
          git --no-pager diff --name-only master staging | grep VERSION
    # - name: Ensure changelog is updated
    #   run: git --no-pager diff --name-only master staging | grep CHANGELOG