name: Cloudbuild Build & Deploy

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build_image:
    name: Build & Deploy GCP Image
    strategy:
      matrix:
        env: [prod, staging]
    runs-on: ubuntu-latest
    steps:
      # setup deps and env vars
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set ${{ matrix.env }} env vars
        if: matrix.env == 'prod'
        run: |
          echo "project_id=logflare-232118" >> "$GITHUB_ENV"
          echo "region=europe-west3" >> "$GITHUB_ENV"
      - name: Set ${{ matrix.env }} env vars
        if: matrix.env == 'staging'
        run: |
          echo "project_id=logflare-staging" >> "$GITHUB_ENV"
          echo "region=us-central1" >> "$GITHUB_ENV"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ matrix.env == 'prod' && secrets.GCP_PROD_CREDENTIALS || secrets.GCP_STAGING_CREDENTIALS }}
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: false
      - uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: "449.0.0"
          project_id: ${{ env.project_id }}

      # run scripts
      - if: github.event_name == 'push' && matrix.env == 'staging'
        run: make deploy.staging.main
      - if: github.event_name == 'workflow_dispatch'
        run: make deploy.${{ matrix.env }}.versioned
